# Generated by Django 4.1.7 on 2024-01-10 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "Course_ID",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("Name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Topics",
            fields=[
                (
                    "Topic_ID",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("Name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "User_ID",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("Name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Prograss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PrograssBar", models.CharField(max_length=30)),
                (
                    "Course_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prog_cid",
                        to="proto.courses",
                    ),
                ),
                (
                    "User_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prog_uid",
                        to="proto.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CTtable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Topics", models.CharField(max_length=10000)),
                (
                    "Course_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ct_cid",
                        to="proto.courses",
                    ),
                ),
            ],
        ),
    ]
