# Generated by Django 4.1.7 on 2024-01-28 16:55

from django.db import migrations, models
import proto.models


class Migration(migrations.Migration):

    dependencies = [
        ("proto", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courses",
            name="Name",
        ),
        migrations.RemoveField(
            model_name="cttable",
            name="Topics",
        ),
        migrations.RemoveField(
            model_name="prograss",
            name="PrograssBar",
        ),
        migrations.RemoveField(
            model_name="topics",
            name="Name",
        ),
        migrations.AddField(
            model_name="courses",
            name="Course_description",
            field=models.CharField(max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name="courses",
            name="Course_name",
            field=models.CharField(default="(*_*)", max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name="courses",
            name="Date_added",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="courses",
            name="Image_link",
            field=models.CharField(default=proto.models.def_img, max_length=150),
        ),
        migrations.AddField(
            model_name="courses",
            name="No_of_enrolment",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cttable",
            name="Course_rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cttable",
            name="Recommended_Time",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cttable",
            name="Related_topic_IDs",
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="cttable",
            name="Topics_IDs",
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="prograss",
            name="Completed_topic_IDs",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="prograss",
            name="Finish_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="prograss",
            name="Incompleted_topic_IDs",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="prograss",
            name="Start_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="topics",
            name="Last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="topics",
            name="Topic_Sources",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="topics",
            name="Topic_description",
            field=models.CharField(max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name="topics",
            name="Topic_name",
            field=models.CharField(default="(*-*)", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="Email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="Join_Date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="Login_map",
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="Password",
            field=models.CharField(default="0000", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="User_image",
            field=models.CharField(default=proto.models.def_img, max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="Username",
            field=models.CharField(default="(^o^)", max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="Name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
