# Generated by Django 4.1.7 on 2024-01-31 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proto", "0002_remove_courses_name_remove_cttable_topics_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="Login_map",
        ),
    ]
