# Generated by Django 4.1.7 on 2024-01-31 17:15

from django.db import migrations, models
import proto1.models


class Migration(migrations.Migration):

    dependencies = [
        ("proto1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "Course_ID",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                (
                    "Course_name",
                    models.CharField(default="(*_*)", max_length=50, unique=True),
                ),
                ("Date_added", models.DateTimeField(auto_now=True)),
                ("No_of_enrolment", models.IntegerField(default=0)),
                ("Course_description", models.CharField(max_length=1200, null=True)),
                (
                    "Image_link",
                    models.CharField(default=proto1.models.def_img, max_length=150),
                ),
            ],
        ),
    ]
