# Generated by Django 5.0.1 on 2024-02-12 04:56

import django.db.models.deletion
import proto3.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('Course_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Course_name', models.CharField(default='(*_*)', max_length=50, unique=True)),
                ('Date_added', models.DateTimeField(auto_now=True)),
                ('No_of_enrolment', models.IntegerField(default=0)),
                ('Course_description', models.CharField(max_length=1200, null=True)),
                ('Image_link', models.CharField(default=proto3.models.def_img, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('Topic_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Topic_name', models.CharField(default='(*-*)', max_length=50)),
                ('Topic_description', models.CharField(max_length=1200, null=True)),
                ('Last_updated', models.DateTimeField(auto_now=True)),
                ('Topic_Sources', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackerUser',
            fields=[
                ('Their_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Their_Username', models.CharField(default='(^o^)', max_length=100)),
                ('Their_Name', models.CharField(max_length=100, null=True)),
                ('Their_Email', models.EmailField(max_length=254, null=True)),
                ('Their_Password', models.CharField(default='0000', max_length=20)),
                ('Their_Join_Date', models.DateTimeField(auto_now=True)),
                ('Their_last_login', models.DateTimeField(auto_now=True)),
                ('Their_Login_map', models.CharField(max_length=10000, null=True)),
                ('Their_User_image', models.CharField(default=proto3.models.def_img, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CTtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topics_IDs', models.CharField(max_length=10000, null=True)),
                ('Related_topic_IDs', models.CharField(max_length=10000, null=True)),
                ('Course_rating', models.IntegerField(default=0)),
                ('Recommended_Time', models.IntegerField(default=0)),
                ('Course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ct_cid', to='proto3.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Completed_topic_IDs', models.CharField(max_length=1000, null=True)),
                ('Incompleted_topic_IDs', models.CharField(max_length=1000, null=True)),
                ('Start_date', models.DateTimeField(auto_now=True)),
                ('Finish_date', models.DateTimeField(auto_now=True)),
                ('Course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prog_cid', to='proto3.courses')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prog_uid', to='proto3.trackeruser')),
            ],
        ),
    ]
