# Generated by Django 5.0.1 on 2024-02-16 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proto3', '0003_rename_completed_topics_progress_completed_topics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cttable',
            name='Topics_IDs',
        ),
        migrations.AddField(
            model_name='cttable',
            name='Topics_ID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ct_tid', to='proto3.topics'),
        ),
    ]
