# Generated by Django 5.0.1 on 2024-02-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proto3', '0005_remove_topics_topic_sources_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cttable',
            name='Course_rating',
        ),
        migrations.RemoveField(
            model_name='cttable',
            name='Recommended_Time',
        ),
    ]
