# Generated by Django 5.0.1 on 2024-02-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proto3', '0007_alter_trackeruser_their_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackeruser',
            name='Their_User_image',
            field=models.ImageField(default='templates/DBMS Project/profile/default.png', upload_to='user_images/'),
        ),
    ]
