# Generated by Django 4.2.10 on 2024-02-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="test",
            fields=[
                ("uid", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("pword", models.CharField(max_length=50)),
            ],
        ),
    ]
