# Generated by Django 4.2.10 on 2024-02-14 08:45

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_profile_delete_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "Course_ID",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                (
                    "Course_name",
                    models.CharField(default="(*_*)", max_length=50, unique=True),
                ),
                ("Date_added", models.DateTimeField(auto_now=True)),
                ("No_of_enrolment", models.IntegerField(default=0)),
                ("Course_description", models.CharField(max_length=1200, null=True)),
                (
                    "Image_link",
                    models.CharField(default=user.models.def_img, max_length=150),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Topics",
            fields=[
                (
                    "Topic_ID",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("Topic_name", models.CharField(default="(*-*)", max_length=50)),
                ("Topic_description", models.CharField(max_length=1200, null=True)),
                ("Last_updated", models.DateTimeField(auto_now=True)),
                ("Topic_Sources", models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="usr",
            new_name="uname",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="stan",
        ),
        migrations.AddField(
            model_name="profile",
            name="Their_Login_map",
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="Their_Name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_img",
            field=models.CharField(default=user.models.def_img, max_length=200),
        ),
        migrations.CreateModel(
            name="Prograss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Completed_topic_IDs", models.CharField(max_length=1000, null=True)),
                ("Incompleted_topic_IDs", models.CharField(max_length=1000, null=True)),
                ("Start_date", models.DateTimeField(auto_now=True)),
                ("Finish_date", models.DateTimeField(auto_now=True)),
                (
                    "Course_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prog_cid",
                        to="user.courses",
                    ),
                ),
                (
                    "User_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prog_uid",
                        to="user.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CTtable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Topics_IDs", models.CharField(max_length=10000, null=True)),
                ("Related_topic_IDs", models.CharField(max_length=10000, null=True)),
                ("Course_rating", models.IntegerField(default=0)),
                ("Recommended_Time", models.IntegerField(default=0)),
                (
                    "Course_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ct_cid",
                        to="user.courses",
                    ),
                ),
            ],
        ),
    ]
