# Generated by Django 4.2.10 on 2024-02-17 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_rename_uname_profile_uid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="Their_Login_map",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="Their_Name",
        ),
    ]
