# Generated by Django 4.2.10 on 2024-02-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_remove_profile_their_login_map_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prograss",
            name="Completed_topic_IDs",
            field=models.CharField(default="0", max_length=1000, null=True),
        ),
    ]
