# Generated by Django 4.2.10 on 2024-02-17 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0006_alter_prograss_completed_topic_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prograss",
            name="User_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prog_uid",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
