# Generated by Django 4.1.7 on 2024-02-04 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proto2", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="Password",
        ),
    ]
